#!/bin/bash
source=$1
target=$2
source_name="source_repo"
target_name="target_repo"

if [[ -n "$source" ]] && [[ -n "$target" ]]; then
	git clone $target $target_name
	cd $target_name
    git clone $source $source_name
	cd $source_name
	rm -rf .git
	mv * ../
	cd ..
	rm -rf $source_name
	git add .
	git commit -m "initial commit"
	git push
else
    echo "usage: move_repo.sh <source> <target>"
fi
